// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/rate": {
            "get": {
                "description": "Запит має повертати поточний курс BTC до UAH використовуючи будь-який third party сервіс з публічним API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rate"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sendEmails": {
            "post": {
                "description": "Запит має отримувати актуальний курс BTC до UAH за допомогою third-party сервісу та відправляти його на всі електронні адреси, які були підписані раніше",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "responses": {
                    "200": {
                        "description": "E-mailʼи відправлено",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Помилка на сервері",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/subscribe": {
            "post": {
                "description": "Запит має перевірити, чи немає данної електронної адреси в поточній базі даних (файловій) і, в разі її відсутності, записувати її. Пізніше, за допомогою іншого запиту ми будемо відправляти лист на ті електронні адреси, які будуть в цій базі.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Електронна адреса, яку потрібно підписати",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Email додано",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Email вже є в базі даних",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Помилка на сервері",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "GSES2 BTC application",
	Description:      "Сервіс з API, який дозволить: \\n- дізнатись поточний курс біткоіну (BTC) у гривні (UAH) \\n- підписати емейл на отримання інформації по зміні курсу \\n- запит, який відправить всім підписаним користувачам актуальний курс.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
